/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeasientos;

import java.util.LinkedList;
import java.util.StringTokenizer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sistemadeasientos.business.Archivo;
import sistemadeasientos.business.ListaAsientos;
import sistemadeasientos.model.ReservacionModel;

/**
 *
 * @author Heber
 */
public class frmBus extends javax.swing.JFrame {

    /**
     * Creates new form frmBus
     */
    
   
    private String nombre;
    private String pAsiento;
    private float precio;
    Icon taken = new ImageIcon(ClassLoader.getSystemResource("sistemadeasientos/resource/T1.png"));
    Icon aviable = new ImageIcon(ClassLoader.getSystemResource("sistemadeasientos/resource/A1.png"));
    private boolean Guardar;
    private ReservacionModel rs;
    private boolean estado;
    private boolean Existe;
    ReservacionModel[] reservaciones;
    
    public frmBus() {
        initComponents();
        CambiarDisponibilidad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnA1 = new javax.swing.JButton();
        btnB0 = new javax.swing.JButton();
        btnC0 = new javax.swing.JButton();
        btnD0 = new javax.swing.JButton();
        btnA0 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnB6 = new javax.swing.JButton();
        btnB7 = new javax.swing.JButton();
        btnC7 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnC6 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD7 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Control de pasajeros - BusTrack ");

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel4.setText("ESTADO DE LOS ASCIENTOS");

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel5.setText("DISPONIBLES");

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel6.setText("OCUPADOS");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/available.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/taken.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Mañana ");

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel2.setText("RUTAS Y HORARIOS");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setText("Tarde");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("Noche ");

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setText("4 am a 11 am");

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setText("12 pm a 6 pm");

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setText("7 pm a 10 pm ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel13))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/busb.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/busA.png"))); // NOI18N

        btnA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        btnB0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB0ActionPerformed(evt);
            }
        });

        btnC0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC0ActionPerformed(evt);
            }
        });

        btnD0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD0ActionPerformed(evt);
            }
        });

        btnA0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA0ActionPerformed(evt);
            }
        });

        btnA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });

        btnA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });

        btnA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });

        btnA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5ActionPerformed(evt);
            }
        });

        btnA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA6ActionPerformed(evt);
            }
        });

        btnA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA7ActionPerformed(evt);
            }
        });

        btnB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1ActionPerformed(evt);
            }
        });

        btnB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2ActionPerformed(evt);
            }
        });

        btnB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB3ActionPerformed(evt);
            }
        });

        btnB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB4ActionPerformed(evt);
            }
        });

        btnB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB5ActionPerformed(evt);
            }
        });

        btnB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB6ActionPerformed(evt);
            }
        });

        btnB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB7ActionPerformed(evt);
            }
        });

        btnC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC7ActionPerformed(evt);
            }
        });

        btnC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });

        btnC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC4ActionPerformed(evt);
            }
        });

        btnC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC6ActionPerformed(evt);
            }
        });

        btnC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC5ActionPerformed(evt);
            }
        });

        btnC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC2ActionPerformed(evt);
            }
        });

        btnC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC1ActionPerformed(evt);
            }
        });

        btnD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD4ActionPerformed(evt);
            }
        });

        btnD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD2ActionPerformed(evt);
            }
        });

        btnD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD7ActionPerformed(evt);
            }
        });

        btnD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD3ActionPerformed(evt);
            }
        });

        btnD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD5ActionPerformed(evt);
            }
        });

        btnD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD1ActionPerformed(evt);
            }
        });

        btnD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeasientos/resource/A1.png"))); // NOI18N
        btnD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnA7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnA6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnB7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnB6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnA5)
                            .addComponent(btnB5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnD7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnD6)
                        .addGap(18, 18, 18)
                        .addComponent(btnD5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnC7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnC6)
                        .addGap(18, 18, 18)
                        .addComponent(btnC5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnC4)
                    .addComponent(btnD4)
                    .addComponent(btnA4)
                    .addComponent(btnB4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnD3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnB3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnD2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnA2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnB2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnD1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnA1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnB1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnD0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnA0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnB0, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnA3)
                                                .addGap(43, 43, 43))
                                            .addComponent(btnB3))
                                        .addGap(53, 53, 53))
                                    .addComponent(btnC3))
                                .addGap(5, 5, 5)
                                .addComponent(btnD3))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnA7)
                                                .addComponent(btnA6))
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnB7)
                                                .addComponent(btnB6))
                                            .addGap(20, 20, 20)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnC7)
                                                .addComponent(btnC6)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(btnA5)
                                                    .addGap(43, 43, 43))
                                                .addComponent(btnB5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnC5)))
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnD5)
                                        .addComponent(btnD7)
                                        .addComponent(btnD6)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(btnA4)
                                                    .addGap(43, 43, 43))
                                                .addComponent(btnB4))
                                            .addGap(53, 53, 53))
                                        .addComponent(btnC4))
                                    .addGap(5, 5, 5)
                                    .addComponent(btnD4)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnA2)
                                                .addGap(43, 43, 43))
                                            .addComponent(btnB2))
                                        .addGap(53, 53, 53))
                                    .addComponent(btnC2))
                                .addGap(5, 5, 5)
                                .addComponent(btnD2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnA1)
                                .addGap(10, 10, 10)
                                .addComponent(btnB1)
                                .addGap(20, 20, 20)
                                .addComponent(btnC1)
                                .addGap(5, 5, 5)
                                .addComponent(btnD1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnA0)
                                .addGap(10, 10, 10)
                                .addComponent(btnB0)
                                .addGap(20, 20, 20)
                                .addComponent(btnC0)
                                .addGap(5, 5, 5)
                                .addComponent(btnD0))))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB6ActionPerformed
        pAsiento = ObtenerAsiento("B6");  
        VerificarDatos("B6");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB6ActionPerformed

    private void btnA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA7ActionPerformed
        pAsiento = ObtenerAsiento("A7");
        VerificarDatos("A7");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA7ActionPerformed

    private void btnA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA6ActionPerformed
        pAsiento = ObtenerAsiento("A6");
        VerificarDatos("A6");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA6ActionPerformed

    private void btnA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5ActionPerformed
        pAsiento = ObtenerAsiento("A5");
        VerificarDatos("A5");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA5ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        pAsiento = ObtenerAsiento("A4");
        VerificarDatos("A4");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        pAsiento = ObtenerAsiento("A2");
        VerificarDatos("A2");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        pAsiento = ObtenerAsiento("A3");
        VerificarDatos("A3");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA0ActionPerformed
        pAsiento = ObtenerAsiento("A0");
        VerificarDatos("A0");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA0ActionPerformed

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        pAsiento = ObtenerAsiento("A1");
        VerificarDatos("A1");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        pAsiento = ObtenerAsiento("C3");
        VerificarDatos("C3");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB7ActionPerformed
        pAsiento = ObtenerAsiento("B7");
        VerificarDatos("B7");
        Guardar = true;        
        AgregarDatos();
    }//GEN-LAST:event_btnB7ActionPerformed

    private void btnC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC7ActionPerformed
       pAsiento = ObtenerAsiento("C7");
       VerificarDatos("C7");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC7ActionPerformed

    private void btnD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD7ActionPerformed
        pAsiento = ObtenerAsiento("D7");
        VerificarDatos("D7");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD7ActionPerformed

    private void btnC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC6ActionPerformed
        pAsiento = ObtenerAsiento("C6");
        VerificarDatos("C6");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC6ActionPerformed

    private void btnD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD6ActionPerformed
        pAsiento = ObtenerAsiento("D6");
        VerificarDatos("D6");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD6ActionPerformed

    private void btnB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB5ActionPerformed
       pAsiento = ObtenerAsiento("B5");
       VerificarDatos("B5");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB5ActionPerformed

    private void btnC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC5ActionPerformed
        pAsiento = ObtenerAsiento("C5");
        VerificarDatos("C5");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC5ActionPerformed

    private void btnD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD5ActionPerformed
        pAsiento = ObtenerAsiento("D5");
        VerificarDatos("D5");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD5ActionPerformed

    private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB4ActionPerformed
        pAsiento = ObtenerAsiento("B4");
        VerificarDatos("B4");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB4ActionPerformed

    private void btnC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC4ActionPerformed
        pAsiento = ObtenerAsiento("C4");
        VerificarDatos("C4");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC4ActionPerformed

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
      pAsiento = ObtenerAsiento("D4");
      VerificarDatos("D4");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3ActionPerformed
        pAsiento = ObtenerAsiento("B3");
        VerificarDatos("B3");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB3ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
        pAsiento = ObtenerAsiento("D3");
        VerificarDatos("D3");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD3ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        pAsiento = ObtenerAsiento("B2");
        VerificarDatos("B2");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        pAsiento = ObtenerAsiento("C2");
        VerificarDatos("C2");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
        pAsiento = ObtenerAsiento("D2");
        VerificarDatos("D2");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD2ActionPerformed

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
       pAsiento = ObtenerAsiento("B1");
       VerificarDatos("B1");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        pAsiento = ObtenerAsiento("C1");
        VerificarDatos("C1");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
        pAsiento = ObtenerAsiento("D1");
        VerificarDatos("D1");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB0ActionPerformed
        pAsiento = ObtenerAsiento("B0");
        VerificarDatos("B0");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnB0ActionPerformed

    private void btnC0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC0ActionPerformed
        pAsiento = ObtenerAsiento("C0");
        VerificarDatos("C0");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnC0ActionPerformed

    private void btnD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD0ActionPerformed
       pAsiento = ObtenerAsiento("D0");
       VerificarDatos("D0");
        Guardar = true;
        AgregarDatos();
    }//GEN-LAST:event_btnD0ActionPerformed

    private void AgregarDatos(){
        frmDatos ingresarDatos; 
        if(Existe){
            ingresarDatos = new frmDatos(this,reservaciones[0].getNombreCliente(),reservaciones[0].getPrecio(),reservaciones[0].getPocision()); 
        }else{
            ingresarDatos = new frmDatos(this,"",0,pAsiento); 
        }
             
        ingresarDatos.show();        
        Existe = false;
    }
    
    public void EliminarDato(String idAsientoD){
         switch(idAsientoD){       
                case "A0":
                    btnA0.setIcon(aviable);
                    break;
                    case "A1":
                    btnA1.setIcon(aviable);
                    break;
                    case "A2":
                    btnA2.setIcon(aviable);
                    break;
                    case "A3":
                    btnA3.setIcon(aviable);
                    break;
                    case "A4":
                    btnA4.setIcon(aviable);
                    break;
                    case "A5":
                    btnA5.setIcon(aviable);
                    break;
                    case "A6":
                    btnA6.setIcon(aviable);
                    break;
                    case "A7":
                    btnA7.setIcon(aviable);
                    break;
                    case "B0":
                    btnB0.setIcon(aviable);
                    break;
                    case "B1":
                    btnB1.setIcon(aviable);
                    break;
                    case "B2":
                    btnB2.setIcon(aviable);
                    break;
                    case "B3":
                    btnB2.setIcon(aviable);
                    break;
                    case "B4":
                    btnB4.setIcon(aviable);
                    break;
                    case "B5":
                    btnB5.setIcon(aviable);
                    break;
                    case "B6":
                    btnB6.setIcon(aviable);
                    break;
                    case "B7":
                    btnB7.setIcon(aviable);
                    break;
                    case "C0":
                    btnC0.setIcon(aviable);
                    break;
                    case "C1":
                    btnC1.setIcon(aviable);
                    break;
                    case "C2":
                    btnC2.setIcon(aviable);
                    break;
                    case "C3":
                    btnC3.setIcon(aviable);
                    break;
                    case "C4":
                    btnC4.setIcon(aviable);
                    break;
                    case "C5":
                    btnC5.setIcon(aviable);
                    break;
                    case "C6":
                    btnC6.setIcon(aviable);
                    break;
                    case "C7":
                    btnC7.setIcon(aviable);
                    break;
                    case "D0":
                    btnD0.setIcon(aviable);
                    break;
                    case "D1":
                    btnD1.setIcon(aviable);
                    break;
                    case "D2":
                    btnD2.setIcon(aviable);
                    break;
                    case "D3":
                    btnD2.setIcon(aviable);
                    break;
                    case "D4":
                    btnD4.setIcon(aviable);
                    break;
                    case "D5":
                    btnD5.setIcon(aviable);
                    break;
                    case "D6":
                    btnD6.setIcon(aviable);
                    break;
                    case "D7":
                    btnD7.setIcon(aviable);
                    break;
            }
    }
    
    private String ObtenerAsiento(String idAsiento){
        if(idAsiento.contains("A") || idAsiento.contains("C")){
            precio = 10;
        }else{
             precio = 5;
        }
        return idAsiento;
    }
    
    public void EnviarDatos(String nombreC){
        nombre = nombreC;
        System.out.println(nombreC);        
        ReservacionModel reservacion = new ReservacionModel(nombreC, false, pAsiento, pAsiento,precio );
        ListaAsientos lst = new ListaAsientos();
        lst.Agregar(reservacion);
        lst.GuardarArchivo();
        CambiarDisponibilidad();
    }
    
    private void CambiarDisponibilidad(){
        ListaAsientos lst = new ListaAsientos();
        int cantidad;
        if(!Guardar){
            lst.cargarProductos();
            cantidad = lst.AllReservacion.length;
        }else{
            cantidad = 1;
        }         
            for(int i=0; i < cantidad; i++ ){
            String idAsientoD = Guardar ? pAsiento : lst.AllReservacion[i].getPocision();
            String test = idAsientoD;
            
            switch(idAsientoD){       
                case "A0":
                    btnA0.setIcon(taken);
                    break;
                    case "A1":
                    btnA1.setIcon(taken);
                    break;
                    case "A2":
                    btnA2.setIcon(taken);
                    break;
                    case "A3":
                    btnA3.setIcon(taken);
                    break;
                    case "A4":
                    btnA4.setIcon(taken);
                    break;
                    case "A5":
                    btnA5.setIcon(taken);
                    break;
                    case "A6":
                    btnA6.setIcon(taken);
                    break;
                    case "A7":
                    btnA7.setIcon(taken);
                    break;
                    case "B0":
                    btnB0.setIcon(taken);
                    break;
                    case "B1":
                    btnB1.setIcon(taken);
                    break;
                    case "B2":
                    btnB2.setIcon(taken);
                    break;
                    case "B3":
                    btnB2.setIcon(taken);
                    break;
                    case "B4":
                    btnB4.setIcon(taken);
                    break;
                    case "B5":
                    btnB5.setIcon(taken);
                    break;
                    case "B6":
                    btnB6.setIcon(taken);
                    break;
                    case "B7":
                    btnB7.setIcon(taken);
                    break;
                    case "C0":
                    btnC0.setIcon(taken);
                    break;
                    case "C1":
                    btnC1.setIcon(taken);
                    break;
                    case "C2":
                    btnC2.setIcon(taken);
                    break;
                    case "C3":
                    btnC3.setIcon(taken);
                    break;
                    case "C4":
                    btnC4.setIcon(taken);
                    break;
                    case "C5":
                    btnC5.setIcon(taken);
                    break;
                    case "C6":
                    btnC6.setIcon(taken);
                    break;
                    case "C7":
                    btnC7.setIcon(taken);
                    break;
                    case "D0":
                    btnD0.setIcon(taken);
                    break;
                    case "D1":
                    btnD1.setIcon(taken);
                    break;
                    case "D2":
                    btnD2.setIcon(taken);
                    break;
                    case "D3":
                    btnD2.setIcon(taken);
                    break;
                    case "D4":
                    btnD4.setIcon(taken);
                    break;
                    case "D5":
                    btnD5.setIcon(taken);
                    break;
                    case "D6":
                    btnD6.setIcon(taken);
                    break;
                    case "D7":
                    btnD7.setIcon(taken);
                    break;
            }
            
        }
        
    }
    
    private void VerificarDatos(String idAsiento){
    
        Archivo archivo = new Archivo("asientos.txt");
        LinkedList<String> lineas = archivo.obtenerTextoDelArchivo();
        if (lineas != null) {
             reservaciones = new ReservacionModel[lineas.size()]; // Crear el arreglo del tamaño adecuado
        for (int i = 0; i < lineas.size(); i++) {
            String linea = lineas.get(i);
            StringTokenizer tokens = new StringTokenizer(linea, ";");
            String nombreCliente = tokens.nextToken();
            estado = Boolean.parseBoolean(tokens.nextToken());
            String posicion = tokens.nextToken();
            String Id = tokens.nextToken();
            float precio = Float.parseFloat(tokens.nextToken());
            
            if(posicion.equals(idAsiento)){
                Existe = true;
                reservaciones[0] = new ReservacionModel(nombreCliente, estado, posicion, Id, precio);
                break;
            }        
            
            
            
        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA0;
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnA6;
    private javax.swing.JButton btnA7;
    private javax.swing.JButton btnB0;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnB5;
    private javax.swing.JButton btnB6;
    private javax.swing.JButton btnB7;
    private javax.swing.JButton btnC0;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnC5;
    private javax.swing.JButton btnC6;
    private javax.swing.JButton btnC7;
    private javax.swing.JButton btnD0;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD5;
    private javax.swing.JButton btnD6;
    private javax.swing.JButton btnD7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
